[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lpagg"
description = "Load profile aggregator for building simulations"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
    { name = "Joris Zimmermann", email = "joris.zimmermann@siz-energieplus.de" }
]
keywords = ["load profile", "aggregator", "building simulation"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "pandas>=2.1",
    "openpyxl>=3.0.3",
    "pyyaml>=5.1",
    "matplotlib",
    "scipy",
    "requests",
    "geopy",
    "holidays>=0.13",
]
dynamic = ["version"]

[project.optional-dependencies]
simlty_GUI = ["PyQt5"]

demandlib = ["https://github.com/oemof/oemof-demand/archive/dev.tar.gz"]

[project.urls]
Homepage = "https://github.com/jnettels/lpagg"
Repository = "https://github.com/jnettels/lpagg"

[project.scripts]
lpagg = "lpagg.__main__:main"

[project.gui-scripts]
simlty_GUI = "lpagg.simlty_GUI:main"

[tool.flit.module]
name = "lpagg"
path = "src"

[tool.flit.sdist]
include = [
    "src/lpagg/",
    "src/lpagg/lpagg.mplstyle",
    "src/lpagg/res/*.ico",
    "src/lpagg/res/*.png",
    "src/lpagg/resources_load/*.xlsx",
    "src/lpagg/resources_weather/*_Jahr.dat",
    "src/lpagg/resources_weather/*.geojson",
    "examples/VDI_4655_config_example.yaml",
    "examples/VDI_4655_houses_example.xlsx",
    "conda.recipe/",
]
