[tox]
envlist = py{312,313}
skip_missing_interpreters = true

[testenv]
deps =
    pytest>=7.0
    pytest-cov
extras = demandlib
description = Run pytest tests
commands =
    pytest tests/ -v --tb=short

[testenv:py{312,313}-cov]
commands =
    pytest tests/ -v --cov=lpagg --cov-report=term-missing --tb=short

[testenv:lint]
deps =
    pylint
skip_install = true
commands =
    pylint src/lpagg

[testenv:type]
deps =
    mypy
commands =
    mypy src/lpagg
