{% set data = load_setup_py_data() %}

package:
  name: lpagg
  version: {{ data['version'] }}

source:
    path: ..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

  entry_points:
    # Put any entry points (scripts to be generated automatically) here.
    - lpagg = lpagg.__main__:main
    - simultaneity = lpagg.simultaneity:main
    - simlty_GUI = lpagg.simlty_GUI:main
    - dwd2trnsys = lpagg.dwd2trnsys:main

requirements:
    build:
        - python
        - setuptools
        - setuptools_scm
        - pandas >=1.2.1

    run:
        - python
        - pandas >=1.2.1
        - openpyxl >=3.0.3
        - pyyaml >=5.1
        - matplotlib
        - scipy
        - requests
        - geopy
        - holidays

test:
  source_files:
    - lpagg/examples/VDI_4655_config_example.yaml
    - lpagg/resources_weather/TRY2010_04_Jahr.dat

about:
    home: https://github.com/jnettels/lpagg
    summary: 'Load profile aggregator for building simulations'
    description: 'Load profile aggregator for building simulations'
    license: 'MIT'
    license_file: LICENSE.txt
    author: 'Joris Zimmermann'
    author_email: 'joris.zimmermann@stw.de'
