name: Publish Releases

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    name: Publish
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.13"]

    steps:
    - name: Checkout
      uses: actions/checkout@v7  # use the latest code commit

    - name: Setup conda with python ${{ matrix.python-version }}
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: false
        python-version: ${{ matrix.python-version }}

    - name: Add conda defaults channel
      run: conda config --add channels defaults

    - name: Initialize powershell for conda (Windows only)
      if: runner.os == 'Windows'
      run: conda init powershell

    - name: Install dependencies with conda
      run: |
        conda install numpy
        conda install anaconda-client conda-build

    - name: Build & upload with conda
      run: |
        # Login to anaconda (answer the resulting prompt with yes)
        echo y | anaconda --token ${{ secrets.ANACONDA_TOKEN }} login --username ${{ secrets.ANACONDA_USERNAME }} --password ${{ secrets.ANACONDA_PASSWORD }} --hostname "lpagg_GitHub_${{ matrix.os }}_${{ matrix.python-version }}"
        # Enable automatic upload to anaconda.org
        conda config --set anaconda_upload yes
        # Run build process
        conda build conda.recipe -c defaults -c conda-forge
