name: tox

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run tox tests
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: '3.12'
            toxenv: py312
          - python-version: '3.13'
            toxenv: py313

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tox
        run: python -m pip install --upgrade pip tox

      - name: Run tox
        run: tox -e ${{ matrix.toxenv }}
